# Import requirements

In [1]:
from sudoku_ml.agent import Agent
from sudoku_ml import datasets
from sudoku_ml import utils as ml_utils

2022-01-30 00:39:22.174419: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# Generate a training dataset

In [20]:
generator = datasets.Generator()
train_dataset = generator.generate_training_dataset(
    count=1000000,
    removed=(10, 50),
)

# Create agent

In [21]:
agent = Agent(
    batch_size=512,
    epochs=2,
)

#  Run training

In [22]:
agent.train(
    runs=1,
    dataset=train_dataset
)

Epoch 1/2
1250/1250 - 491s - loss: 0.3496 - val_loss: 0.2068 - 491s/epoch - 393ms/step
Epoch 2/2
1250/1250 - 468s - loss: 0.1881 - val_loss: 0.1826 - 468s/epoch - 375ms/step


## Save the model

In [24]:
agent.model.save('/tmp/sudoku.h5')

# Run inference
## Generate a grid

In [28]:
puzzle, solution = generator.generate_dataset(
    count=1,
    removed=(10, 50),
)
print(puzzle.reshape(9, 9))
print(solution.reshape(9, 9)+1)

[[9 0 0 1 7 6 4 8 5]
 [8 0 0 3 0 2 1 0 6]
 [7 0 1 0 0 5 3 9 0]
 [5 1 7 8 2 0 0 6 0]
 [2 4 8 0 0 3 7 5 1]
 [0 3 0 7 5 1 0 2 4]
 [1 0 0 5 0 0 0 0 0]
 [4 7 5 0 0 8 0 1 9]
 [3 0 0 0 1 9 0 0 0]]
[[9 2 3 1 7 6 4 8 5]
 [8 5 4 3 9 2 1 7 6]
 [7 6 1 4 8 5 3 9 2]
 [5 1 7 8 2 4 9 6 3]
 [2 4 8 9 6 3 7 5 1]
 [6 3 9 7 5 1 8 2 4]
 [1 9 6 5 4 7 2 3 8]
 [4 7 5 2 3 8 6 1 9]
 [3 8 2 6 1 9 5 4 7]]


## Solve

In [38]:
grid = puzzle.copy()

while not grid.all():
    X, Y, value = agent.infer(grid)
    is_valid = solution.reshape((9, 9))[X, Y] == value
    print(X, Y, value+1, is_valid)
    if not is_valid:
        break
    grid.reshape(9, 9)[X, Y] = value + 1
    
print(grid.reshape(9, 9))

3 5 4 True
1 2 4 True
1 7 7 True
1 1 5 True
3 8 3 True
5 0 6 True
1 4 9 True
2 3 4 True
2 4 8 True
2 8 2 True
4 4 6 True
4 3 9 True
7 4 3 True
6 4 4 True
6 5 7 True
6 7 3 True
8 7 4 True
2 1 6 True
0 2 3 True
0 1 2 True
8 1 8 True
6 1 9 True
6 8 8 True
8 8 7 True
3 6 9 True
5 2 9 True
5 6 8 True
7 3 2 True
8 3 6 True
7 6 6 True
6 6 2 True
6 2 6 True
8 2 2 True
8 6 5 True
[[9 2 3 1 7 6 4 8 5]
 [8 5 4 3 9 2 1 7 6]
 [7 6 1 4 8 5 3 9 2]
 [5 1 7 8 2 4 9 6 3]
 [2 4 8 9 6 3 7 5 1]
 [6 3 9 7 5 1 8 2 4]
 [1 9 6 5 4 7 2 3 8]
 [4 7 5 2 3 8 6 1 9]
 [3 8 2 6 1 9 5 4 7]]
